package db;

import dao.CollaboratorDAO;
import dao.CollaboratorDAOImpl;
import dao.TaskDAOImpl;
import entity.Collaborator;
import entity.Task;
import entity.TaskStatus;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

public class DBTest {
    public static void main(String[] args) {
        Connection connection = DBHelper.getConnection();
        try {
            Statement statement = connection.createStatement();
            String sql;
            //sql = "CREATE TABLE collaborator (id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) , surname VARCHAR(255), name VARCHAR(255), patronymic VARCHAR(255), position VARCHAR(255))";
            //statement.execute(sql);

//            Collaborator collaborator = new Collaborator("Novikov", "Alex", "Petrovich", "Director");
//            Collaborator newCollaborator = new Collaborator("e", "e", "e", "e");
//            collaborator.setId(1);
//            new CollaboratorDAOImpl().updateCollaborator(collaborator, newCollaborator);
//
//
//            ArrayList<Collaborator> collaborators = (ArrayList<Collaborator>) new CollaboratorDAOImpl().getCollaborators();
//
//            for (Collaborator collaborator1 : collaborators) {
//                System.out.println(collaborator1);
//            }
            ArrayList<Task> tasks = (ArrayList<Task>) new TaskDAOImpl().getTasks();
            for(Task task : tasks){
                System.out.println(task);
                System.out.println(task.getCollaborator());
                System.out.println(task.getProject());
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
